var name = ['Lawrence', 'Mike', 'Mehul', 'Irene', 'Summer', 'Nadine', 'Stacy', 'Simone', 'Andrea', 'Gabby', 'David', 'Faridh', 'Shilpi', 'Igor', 'Val', 'Rosalyn', 'Max', 'Sara', 'Warren', 'Helen'];

var profile = ["https://s3-us-west-1.amazonaws.com/fec-futon/1.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/2.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/3.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/4.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/5.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/6.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/7.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/8.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/9.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/10.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/11.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/12.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/13.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/14.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/15.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/16.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/17.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/18.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/19.jpeg", "https://s3-us-west-1.amazonaws.com/fec-futon/20.jpeg"];

var month = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

var year = [2017, 2018];

var review = [
  'Such a beautiful place! Perfect for a couple (or 2) or a family. 2 bedroom/2 bath. Amazing pool and grounds. We spent everyday in the beautiful pool. There are staff to keep everything clean too. Tari is there everyday and can cook all of your meals- such a good cook! Absolutely want to return. It is a way back from the main road so scooters are a must. These were arranged for us by the owners for $5/day. Alternately, the staff were able to easily assist in getting a taxi our first day so we could go to the supermarket.', 
  'The villa is exactly as you see in the pictures therefore be rest assured there are no hidden nasty surprises on your arrival. One thing we would like to highlight is that if travelling with young children you have to hire a car to move around as shops, restaurants, ATM etc are not really walking distance. If you are travelling on your own or as a couple then definitely a scooter is recommended.', 
  'In Lovina, you found Lov... Everything was great, from the 1st contacts of booking to the departure. Willem is kind and precious man. He assisted us from the very beginning. Tari, the cook and also house-made is so sweet, her food is AMAZING, she prepared breakfast and also lunch and diner at our convenience. The villa is much more beautiful and spacy than it appears on pictures. It is lovely decorated and the garden + pool are amazing. The “center” Lovina is at 5 min by motorbike (delivred at the villa) and you can find the beach, restaurants, supermarkets and tour guides, absolutely all you need. Lovina is a quite place in North Bali with a lot of thingd to do and visit around. I definitely recommend. 100% !!! Thank you Willem and Tari❤️', 
  'It’s look same as pic they posted.',
  'We had a fab time in the villa of Wil and Toos. It is very clean and the hosts have a clear sense of detail. We loved iit and hope to go back one day.',
  'Great house and pool for relaxing days. Breakfast and diner prepared by Tari was excellent. The house was very clean and the host was always available and helpful. We had a great time there and can strongly recommend the Vila Kupu Kupu',
  'It was amazing! We had a great time. We didn\'t need to worry about anything. We rented a scooter and drove around the beautiful area! The pool is the best pool ever and the staff is really really nice. Tari cooked food for us whenever we asked (in advance). We lived in royalty for a week!',
  'Staying at Villa Kupu Kupu was a blast! The Villa is simply amazing as well as the people owning it and working there! i can surely recommend it',
  'A very beautiful villa, a beautiful garden, always a clean pool (the gardener cleans it daily), inside the villa nice bedrooms, everything is very clean, every day Tari prepares delicious breakfasts for lunches and dinners, we order a driver, rent motobike , choose a tour of the island,staff will be helped us with everything, we spent three weeks in this beautiful villa and everything was fine!!thank you so much villa Kupu Kupu!!))',
  'The location is a little far from the central unless you have a car/scooter but thanks to the warm hosts we managed to get in touch with a local to send us around :) tari was an amazing and friendly staff who really helped us with all the contacting of car/scooter rentals, tours etc. The villa is super beautiful, clean & all in all it was such a good stay! Will definitely recommend this to everyone :)',
  'Such a great place!!! Wonderful decor! We loved the view from our bed room and we enjoyed it so much! Just wish if the hot water can running a bit longer! Thanks for all the warm welcome and help during our stayed, for sure we will be back.',
  'Just Wow! We’ve travelled to many countries and stayed at many hotels/villas. But this bamboo house is one of the best! When you stay here you will be one with nature. The view is inbelievable. You hear sounds of the river, the animals even insects all the time. The house is open concept all you see is the beauty of nature. The architecture of this house is amazing! The bedrooms are downstairs and the pool is on the bottom floor. The service is great. They are prompt and friendly. The food is also delicious and reasonable price. The house is sparkly clean. I highly recommend this house.',
  'The accommodation was great and the whole experience in Green Village was absolutely amazing. Reception and catering staff was friendly and helpful. I would recommend this pace to my friend.',
  'The house is even more breathtaking than the photos suggest. Stunning home, great service and communication by the staff. Beautiful location, away from the hectic Balinese towns but close enough to get a taxi anywhere to shop and sightsee. All in all perfect!',
  'Beautiful bamboo house in the jungle, great architectural and natural experience, however beware of insects given that the house is open to the jungle. Unfortunately there were few opportunities to get to know more about the vision of green village/green school, the bamboo house constructions etc. Additionally the service was not great: early notice for food, partly cold/wrong, high service charge.',
  'This is the most stunning place I\'ve ever stayed. The architecture is unreal and the attention to detail is ridiculous. The sound of the river is soothing and rejuvenating and the bedrooms are common areas are all so comfortable, spacious and relaxing. The food was also excellent, especially the jackfruit steak -- wow! Will definitely be coming back here one day.',
  'This is the most stunning place I\'ve ever stayed. The architecture is unreal and the attention to detail is ridiculous. The sound of the river is soothing and rejuvenating and the bedrooms are common areas are all so comfortable, spacious and relaxing. The food was also excellent, especially the jackfruit steak -- wow! Will definitely be coming back here one day.',
  'This sunrise house is amazing, completely open air in nature experience. Out shone our expectations with its space and design. It also had a pool along with three amazing bedrooms and a really nice open plan living space! Just beautiful and scerene!',
  'This accommodation is a must! myself and a friend stayed for a short 2 nights & it left us dreaming of our return. I was worried about mosquito\'s etc but I found if you keep yourself protected and pull the blinds before dark we had no issues at all :) The service & food were great, recommend bringing a few snacks :) . We would recommend this stay to all our friends wanting a lush unique and peaceful get away',
  'Staff is absolutely helpful. The village is stunning architecture but the arounds are very impressive. Though didn’t expect for perfect hotel service, all needs were really conveniently met and room is very clean. Also go sited green school nearby - a perfect experience for family and friends.'
]

module.exports = {
  name,
  profile,
  month,
  year,
  review
}